packages:
  - 'packages/*'

overrides:
  'yaml@>=2.0.0 <2.8.3': 2.8.3

allowBuilds:
  esbuild: true
  mongodb-memory-server: true

minimumReleaseAgeExclude:
  - i18next@26.4.1
  - react-i18next@17.0.13
